/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.Enumeration;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author Bananawaga
 */
public class BMI extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio5
     */
    public BMI() {
        initComponents();
    }
private void calculatingBMI(){
    Double weight = Double.parseDouble(txtfieldWeight.getText());
    Double height = Double.parseDouble(txtfieldHeight.getText());
    Double imc = weight / (height * height);
    // We are giving format to the result
    String result = String.format("%6.2f", imc);
    txtfieldBMI.setText(result);
}
private void showMessage(){
    JRadioButton genderSelected = getRadioButtonSelected(btnGenero);
    String phrase = "Hello " + txtfieldName.getText() + " " + txtfieldSurname.getText() + "," + " your body mass index is: " + txtfieldBMI.getText();
    txtfieldResult.setText(phrase);
}
public static JRadioButton getRadioButtonSelected(ButtonGroup bg){
    for (Enumeration listRB = bg.getElements(); listRB.hasMoreElements();)
    {
         JRadioButton rb = (JRadioButton)listRB.nextElement();
        if (rb.getModel() == bg.getSelection()){
            return rb;
        }  
    }
    return null;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenero = new javax.swing.ButtonGroup();
        panelInfo_usuario = new javax.swing.JPanel();
        labelData = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelSurname = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        txtfieldName = new javax.swing.JTextField();
        txtfieldSurname = new javax.swing.JTextField();
        radiobtnMasculine = new javax.swing.JRadioButton();
        radiobtnFeminine = new javax.swing.JRadioButton();
        radiobtnOther = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelBMI = new javax.swing.JPanel();
        labelHeight = new javax.swing.JLabel();
        labelWeight = new javax.swing.JLabel();
        txtfieldWeight = new javax.swing.JTextField();
        txtfieldHeight = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        labelBMI = new javax.swing.JLabel();
        txtfieldBMI = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        scrllpanelResult = new javax.swing.JScrollPane();
        txtfieldResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelData.setText("ENTER YOUR DATA");

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Name:");

        labelSurname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSurname.setText("Surname:");

        labelGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelGender.setText("Gender:");

        txtfieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldNameActionPerformed(evt);
            }
        });

        txtfieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldSurnameActionPerformed(evt);
            }
        });

        btnGenero.add(radiobtnMasculine);
        radiobtnMasculine.setText("Masculine");

        btnGenero.add(radiobtnFeminine);
        radiobtnFeminine.setText("Feminine");

        btnGenero.add(radiobtnOther);
        radiobtnOther.setText("Other");

        javax.swing.GroupLayout panelInfo_usuarioLayout = new javax.swing.GroupLayout(panelInfo_usuario);
        panelInfo_usuario.setLayout(panelInfo_usuarioLayout);
        panelInfo_usuarioLayout.setHorizontalGroup(
            panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfo_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfo_usuarioLayout.createSequentialGroup()
                        .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSurname)
                            .addComponent(labelName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfieldName)
                            .addComponent(txtfieldSurname)))
                    .addGroup(panelInfo_usuarioLayout.createSequentialGroup()
                        .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelData)
                            .addGroup(panelInfo_usuarioLayout.createSequentialGroup()
                                .addComponent(labelGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radiobtnMasculine, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(radiobtnFeminine, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radiobtnOther, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
        );
        panelInfo_usuarioLayout.setVerticalGroup(
            panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfo_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSurname)
                    .addComponent(txtfieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfo_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGender)
                    .addComponent(radiobtnMasculine, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiobtnFeminine, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiobtnOther, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelHeight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelHeight.setText("Height (m):");

        labelWeight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWeight.setText("Weight (kg):");

        txtfieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldWeightActionPerformed(evt);
            }
        });

        txtfieldHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldHeightActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalculate.setText("Calculate BMI");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        labelBMI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelBMI.setText("BMI:");

        txtfieldBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldBMIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBMILayout = new javax.swing.GroupLayout(panelBMI);
        panelBMI.setLayout(panelBMILayout);
        panelBMILayout.setHorizontalGroup(
            panelBMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBMILayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelHeight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelWeight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(panelBMILayout.createSequentialGroup()
                .addGroup(panelBMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBMILayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBMILayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(labelBMI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfieldBMI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBMILayout.setVerticalGroup(
            panelBMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBMILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWeight)
                    .addComponent(txtfieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBMI)
                    .addComponent(txtfieldBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        scrllpanelResult.setViewportView(txtfieldResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrllpanelResult)
                    .addComponent(panelInfo_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBMI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllpanelResult, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldNameActionPerformed

    private void txtfieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldSurnameActionPerformed

    private void txtfieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldWeightActionPerformed

    private void txtfieldHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldHeightActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btnCalculate)
            calculatingBMI();
            showMessage();
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtfieldBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldBMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldBMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.ButtonGroup btnGenero;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBMI;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelHeight;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSurname;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JPanel panelBMI;
    private javax.swing.JPanel panelInfo_usuario;
    private javax.swing.JRadioButton radiobtnFeminine;
    private javax.swing.JRadioButton radiobtnMasculine;
    private javax.swing.JRadioButton radiobtnOther;
    private javax.swing.JScrollPane scrllpanelResult;
    private javax.swing.JTextField txtfieldBMI;
    private javax.swing.JTextField txtfieldHeight;
    private javax.swing.JTextField txtfieldName;
    private javax.swing.JTextField txtfieldResult;
    private javax.swing.JTextField txtfieldSurname;
    private javax.swing.JTextField txtfieldWeight;
    // End of variables declaration//GEN-END:variables
}
